### ISSUE TITLE
Docker file doesn't work

### ISSUE THREAD

**Issue by mahajamil5** [globaleaks/globaleaks-docker-scripts#1]
Dears Follow Developers,

I've built the docker file then used the image but every time I run the container the application exit out and isn't responsive, your kind assistant is highly appreciated. 

Container logs:

/usr/lib/python2.7/dist-packages/supervisor/options.py:461: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
  INFO Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
  INFO RPC interface 'supervisor' initialized
  CRIT Server 'unix_http_server' running without any HTTP authentication checking
  INFO supervisord started with pid 1
  INFO spawned: 'tor' with pid 8
  INFO spawned: 'globaleaks' with pid 9
  INFO exited: globaleaks (exit status 2; not expected)
  INFO success: tor entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
  INFO spawned: 'globaleaks' with pid 11
  INFO exited: globaleaks (exit status 2; not expected)
  INFO spawned: 'globaleaks' with pid 13
  INFO exited: globaleaks (exit status 2; not expected)
  INFO spawned: 'globaleaks' with pid 15
  INFO exited: globaleaks (exit status 2; not expected)
  INFO gave up: globaleaks entered FATAL state, too many start retries too quickly

Thank you!

**Comment by evilaliv3** [comment]
>
>
Thank you for reporting this.

Actually this set of scripts was just developed for testing purposes and we
currently do not consider that they could be reused right away as they are
not probably mature enough and continuously tested.

Please feel free to test them and propose any improvement that in your
experience you would like to suggest .

Thank you

**Comment by mahajamil5** [comment]
Dear @evilaliv3,

Kindly check the dockerfile I've inspired by your old ones mixed with the new which is running but didn't fully tested it yet. 
But unfortunately, I'm facing another problem how can I specify the Globaleaks version I wanted to donwload since the link http://deb.globaleaks.org has a lot of packages not sure what I need to run the software.  

`FROM debian:10
 
RUN apt-get update -q && \
    apt-get install -y gpg curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN echo "deb http://deb.globaleaks.org bionic/" > /etc/apt/sources.list.d/globaleaks.list
RUN curl -sS https://deb.globaleaks.org/globaleaks.asc | apt-key add -
RUN apt-get update -q && \
    apt-get install -y globaleaks && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
 
VOLUME [ "/var/globaleaks/" ]
EXPOSE 80
EXPOSE 443
 
ADD data/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
CMD ["/usr/bin/supervisord"]
 
CMD /usr/bin/python3 /usr/bin/globaleaks --ip=0.0.0.0 --user=globaleaks  --working-path=/var/globaleaks/ -n`

**Comment by JStyle21** [comment]
@mahajamil5 Did you close it because it was resolved or because no one helped you?
